compiler:
    solc:
        version: 0.8.6
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3"

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.3
